/*
 * conf_tc.h
 *
 * Created: 30/10/2014 10:33:23
 *  Author: Suburban
 */ 

#ifndef CONF_TC_H_
#define CONF_TC_H_

#define TC_CHANNEL_0 0
#define TC_CHANNEL_1 1
#define TC_CHANNEL_2 2

//TC0 Ch 0
#define PIN_PWM_00_A		PIN_PA08B_TC0_A0	//EXT3_PIN_7
#define PIN_PWM_00_A_M		MUX_PA08B_TC0_A0
#define PIN_PWM_00_B		PIN_PA09B_TC0_B0	//EXT3_PIN_8
#define PIN_PWM_00_B_M		MUX_PA09B_TC0_B0

//TC0 Ch 1
#define PIN_PWM_01_A		PIN_PA10B_TC0_A1	//EXT3_PIN_10
#define PIN_PWM_01_A_M		MUX_PA10B_TC0_A1
#define PIN_PWM_01_B		PIN_PA11B_TC0_B1	//EXT4_PIN_15
#define PIN_PWM_01_B_M		MUX_PA11B_TC0_B1

//TC0 Ch 2
#define PIN_PWM_02_A		PIN_PA12B_TC0_A2	//EXT4_PIN_7
#define PIN_PWM_02_A_M		MUX_PA12B_TC0_A2
#define PIN_PWM_02_B		PIN_PA13B_TC0_B2	//EXT4_PIN_8
#define PIN_PWM_02_B_M		MUX_PA13B_TC0_B2

//TC1 Ch 0
#define PIN_PWM_10_A		PIN_PC15A_TC1_A0	//EXT3_PIN_5
#define PIN_PWM_10_A_M		MUX_PC15A_TC1_A0
#define PIN_PWM_10_B		PIN_PC16A_TC1_B0	//EXT3_PIN_6
#define PIN_PWM_10_B_M		MUX_PC16A_TC1_B0

//unused
//TC1 Ch 1
#define PIN_PWM_11_A		PIN_PC17A_TC1_A1	//EXT4_PIN_5
#define PIN_PWM_11_A_M		MUX_PC17A_TC1_A1
#define PIN_PWM_11_B		PIN_PC18A_TC1_B1	//EXT4_PIN_6
#define PIN_PWM_11_B_M		MUX_PC18A_TC1_B1

//unused
//TC1 Ch 2
#define PIN_PWM_12_A		PIN_PC04D_TC1_A2	//EXT2_PIN_7
#define PIN_PWM_12_A_M		MUX_PC04D_TC1_A2
#define PIN_PWM_12_B		PIN_PC05D_TC1_B2	//EXT2_PIN_8
#define PIN_PWM_12_B_M		MUX_PC05D_TC1_B2

//#define TC_PWM_TIMER_SELECTION TC_CMR_TCCLKS_TIMER_CLOCK1
//#define TC_PWM_TIMER_SELECTION TC_CMR_TCCLKS_TIMER_CLOCK2
#define TC_PWM_TIMER_SELECTION TC_CMR_TCCLKS_TIMER_CLOCK3
//#define TC_PWM_TIMER_SELECTION TC_CMR_TCCLKS_TIMER_CLOCK4
//#define TC_PWM_TIMER_SELECTION TC_CMR_TCCLKS_TIMER_CLOCK5

//#define TC_PWM_DIVISOR	1		//corresponds to TC_CMR_TCCLKS_TIMER_CLOCK1
//#define TC_PWM_DIVISOR	2		//corresponds to TC_CMR_TCCLKS_TIMER_CLOCK2	=> 24Mhz clock 
#define TC_PWM_DIVISOR	8			//corresponds to TC_CMR_TCCLKS_TIMER_CLOCK3	=> 6Mhz clock 
//#define TC_PWM_DIVISOR	32		//corresponds to TC_CMR_TCCLKS_TIMER_CLOCK4	=> 1.5Mhz clock 
//#define TC_PWM_DIVISOR	128		//corresponds to TC_CMR_TCCLKS_TIMER_CLOCK5	=> 375Khz clock

//48Mhz / TC_PWM_DIVISOR = 2   / 0xFFFF = 366hz  <=== minimum freq for TC_CMR_TCCLKS_TIMER_CLOCK2
//48Mhz / TC_PWM_DIVISOR = 8   / 0xFFFF = 92hz   <=== minimum freq for TC_CMR_TCCLKS_TIMER_CLOCK3
//48Mhz / TC_PWM_DIVISOR = 32  / 0xFFFF = 23hz   <=== minimum freq for TC_CMR_TCCLKS_TIMER_CLOCK4
//48Mhz / TC_PWM_DIVISOR = 128 / 0xFFFF = 6hz    <=== minimum freq for TC_CMR_TCCLKS_TIMER_CLOCK5

#define TC_PWM_FREQUENCY   500	//Hz
#define TC_PWM_DUTY_CYCLE  0	//%

#endif /* CONF_TC_H_ */